print ('=================================================')
print ('|                  INPUT BENDA                  |')                                                                
print ('=================================================')

print('')
nama_benda = input("nama benda: ")
jumlah = int(input("jumlah benda: "))
besar = float(input("besar arus/tegangan: "))
fungsi = input("fungsi benda: ")
jenis = input("jenis benda:")

print ('================================================')
print('')
print('variabel nama benda  : ',nama_benda)
print('type                 : ',type(nama_benda))
print('variabel jumlah      : ',jumlah)
print('type                 : ',type(jumlah))
print('variable jenis benda :',jenis)
print('type                 :',type(jenis))
print('variabel besar arus  : ',besar)
print('type                 : ',type(besar))
print('variabel fungsi      : ',fungsi)
print('type                 : ',type(fungsi))
print('')
print ('=================================================')
hasil_data = [nama_benda, jumlah, jenis, besar, fungsi]
print ("hasil gabungan data benda = ",hasil_data)
print('')
print ('                        ***                      ')
